### ISSUE TITLE
readthedocs compile error

### ISSUE THREAD

**Issue by decarlof** [tomography/xfluo#19]
@aglowacki build the docs gives an error in the xfluo.models.element_table  module at

def headerData(self, section: int, orientation: QtCore.Qt.Orientation, role: int = ...):
                                ^
SyntaxError: invalid syntax

can you please have  a look?

**Comment by decarlof** [comment]
@aglowacki for now I commented out the call

**Comment by aglowacki** [comment]
How are you building the docs? When I run make html I get a segfault instead of an error message.

**Comment by decarlof** [comment]
I use sphynx (https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html) 

once is installed you 

cd docs
make clean
make html

then you can inspect the result opening with the browser the built folder


francesco

**Comment by aglowacki** [comment]
I had to update my sphinx version . I was able to build without the error you stated above. I t says build finished. 

Are you still getting the error?

**Comment by decarlof** [comment]
I am not getting the error because I commented out  xfluo.models.element_table module at

def headerData(self, section: int, orientation: QtCore.Qt.Orientation, role: int = ...):

**Comment by aglowacki** [comment]
Please see pull request #31

**Comment by decarlof** [comment]
solved

**Comment by decarlof** [comment]
for the record [this is the readthedoc](https://readthedocs.org/projects/xfluo/builds/8993783/) build that failed with the syntax error at

def headerData(self, section: int, orientation: QtCore.Qt.Orientation, role: int = ...):
^
SyntaxError: invalid syntax

**Comment by aglowacki** [comment]
@decarlof  Looking at that link it looks like read the docs is defaulting to python 2.7
line 5: python2.7 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/xfluo/envs/

Looking at
http://blog.readthedocs.com/python-36-support/
 https://docs.readthedocs.io/en/stable/config-file/v1.html

I think if we add the version 3.6 under the python tag if will use python 3.6 and should pass. 

I don't know to test the read the docs build

**Comment by decarlof** [comment]
I just rebuilt your (@aglowacki) fork [here](https://readthedocs.org/projects/xfluo-arthur/builds/9022672/)  and readthedocs is using python3.7 so I would say that some other change (not the recent meta.yaml) fixed the problem. Perhaps the change is setup.py by @sichendart [here](https://github.com/tomography/xfluo/commit/8281d617c3401fa2d4722b48d77969f1332e706f) ?

**Comment by aglowacki** [comment]
If it works from a previous fix then I'm going to close the issue.
