### ISSUE TITLE
dropdown menus of "File", "Edit" and "Save items" do not work on mac any more

### ISSUE THREAD

**Issue by sichendart** [tomography/xfluo#28]
I suspect that some changes made since 4/29 caused the problem, but not sure which in particular.

**Comment by sichendart** [comment]
It seems to be a mac issue, unrelated to the software.

**Comment by decarlof** [comment]
I tried  save/projection on a MAC and it seems to work. I get folders for the selected elements with tiff inside.

**Comment by sichendart** [comment]
Yes, works fine now. Thanks for trying!

**Comment by decarlof** [comment]
great!
